### ISSUE TITLE
RuntimeError: invalid argument 0

### ISSUE THREAD

**Issue by exitxingling** [hou-yz/open-reid-PCB_n_RPP#1]
Traceback (most recent call last):
  File "examples/PCB_n_RPP.py", line 350, in <module>
    main(parser.parse_args())
  File "examples/PCB_n_RPP.py", line 206, in main
    top1 = evaluator.evaluate(val_loader, dataset.val, dataset.val)
  File "/home/celxing/celine_rpp/lib/python3.6/site-packages/open_reid-0.2.0-py3.6.egg/reid/evaluators.py", line 119, in evaluate
  File "/home/celxing/celine_rpp/lib/python3.6/site-packages/open_reid-0.2.0-py3.6.egg/reid/evaluators.py", line 54, in pairwise_distance
RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 0. Got 384 and 78 in dimension 1 at /pytorch/torch/lib/TH/generic/THTensorMath.c:2897
这是什么问题？

**Comment by hou-yz** [comment]
as the RuntimeError suggested, there seems to be a mismatch in the (H\*W) dimension (dimension 1 in the tensor). it's except to have H\*W=24\*8=384, however, it seems that the data you fed in have H\*W=78.

it would be nice if you can provide your scripts so that I can run those scripts and help you find out the exact error!

I don't know if this helps, so if you have further questions, please tell me!

**Comment by exitxingling** [comment]
I just git clone your project ,and do the steps follow your readme.txt document ,and the IDE.py can work, but the PCB model cannot, I use the python3.6 and pytorch 0.4.0, maybe it's the environment issues?

**Comment by exitxingling** [comment]
I have send you an email including my telephone number,If you can freely communicate with me on the phone, I will be grateful. hoping for your reply. thank you!

**Comment by hou-yz** [comment]
I've pushed a new version for BUG fixes, @exitxingling please check it out!
